"""
Django settings for cointop project.

Generated by 'django-admin_cointop startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import pathlib
import typing

BASE_DIR: typing.Final[pathlib.Path] = pathlib.Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY: typing.Final[
    str
] = "django-insecure-d4@e!*ltbljyrt_9hbmy%%vtg15r$pwfj*-a0=qz=akba!a&05"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG: typing.Final[bool] = True

ALLOWED_HOSTS: typing.Final[typing.List[str]] = []


# Application definition

INSTALLED_APPS: typing.Final[typing.List[str]] = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_crontab",
    #     Custom app
    "admin_cointop",
    "cointop",
]

MIDDLEWARE: typing.Final[typing.List[str]] = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # "admin_cointop.middleware.LoginRequiredMiddleware",
]

ROOT_URLCONF: typing.Final[str] = "admin_cointop.urls"

TEMPLATES: typing.Final[
    typing.List[
        typing.Dict[
            str,
            typing.Union[
                str, bool, typing.List[pathlib.Path], typing.Dict[str, typing.List[str]]
            ],
        ]
    ]
] = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION: typing.Final[str] = "admin_cointop.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES: typing.Final[
    typing.Dict[str, typing.Dict[str, typing.Union[str, pathlib.Path]]]
] = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Cache
CACHES: typing.Final[typing.Dict[str, typing.Dict[str, str]]] = {
    "default": {
        "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
        "LOCATION": "/var/tmp/django_cache",
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS: typing.Final[typing.List[typing.Dict[str, str]]] = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE: typing.Final[str] = "en-us"

TIME_ZONE: typing.Final[str] = "UTC"

USE_I18N: typing.Final[bool] = True

USE_TZ: typing.Final[bool] = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL: typing.Final[str] = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD: typing.Final[str] = "django.db.models.BigAutoField"

LOGIN_REDIRECT_URL: typing.Final[str] = "/"
LOGOUT_REDIRECT_URL: typing.Final[str] = "/accounts/login"

# Logging

LOGGING: typing.Final[
    typing.Dict[
        str,
        typing.Union[
            int,
            bool,
            typing.Dict[str, typing.Dict[str, str]],
            typing.Dict[str, typing.Union[typing.List[str], str]],
        ],
    ]
] = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "DEBUG",
    },
}

# Cronjobs

CRONJOBS: typing.Final[typing.List[typing.Tuple[str, str]]] = [
    ("*/30 * * * *", "cointop.cronjobs.alert")
]

# CoinApi

COIN_API_KEY: typing.Final[str] = "8983016B-81B3-41B2-81C5-5567590CDC0D"
COIN_API_ENDPOINT: typing.Final[str] = "https://rest.coinapi.io/v1"
