# Generated by Django 4.2.2 on 2023-07-02 07:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cointop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="asset",
            field=models.CharField(choices=[], max_length=7),
        ),
        migrations.AlterField(
            model_name="alert",
            name="user",
            field=models.ManyToManyField(
                related_name="alerts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
